/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BarcodeScanner: typeof import('./src/components/BarcodeScanner.vue')['default']
    ErrorCard: typeof import('./src/components/ErrorCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutsModal: typeof import('./src/components/ShortcutsModal.vue')['default']
  }
}
